version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: op_devil_fruits_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
     - "5433:5432" # using non default port 5433 to not conflict with the characters service
