server:
  port: 8081 # using a non default port to not conflict with the characters service

spring:
  application:
    name: onepiece_devilfruits
  config:
    import:
      - classpath:devilfruits-data.yml
      - optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5433/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
